# BUILD STAGE
FROM golang:1.19 as build-stage

ENV GOOS linux
ENV CGO_ENABLED 0
WORKDIR /backend

COPY go.mod go.sum ./
RUN go mod download
COPY . ./

RUN go build -o lh_backend

# TEST STAGE
FROM build-stage as run-test-stage
ENV GIN_MODE=test
RUN go test ./...

# PROD STAGE
FROM scratch

WORKDIR /backend
COPY --from=build-stage /backend/lh_backend /backend/lh_backend
ENV GIN_MODE=release

EXPOSE 8080

ENTRYPOINT [ "/backend/lh_backend" ]
